name: Build Docker

on:
  push:
    branches: [ "master", "main", "develop" ]
  pull_request:
    branches: [ "master", "main", "develop" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: GHCR
        uses: macbre/push-to-ghcr@v12
        with:
          github_token: secrets.GITHUB_TOKEN
          image_name: jimbrig/property_allocation_demo
          dockerfile: ./Dockerfile
          context: .
          repository: ghcr.io
          docker_io_user: github.actor
          # docker_io_token: 
          image_tag: latest
